version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: url-shortener-db
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: url-shortener-service
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    ports:
      - '8000:8000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
